<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countryIndiaId = 82;
        $countryUSAId = 191;

        DB::table('states')->insert([
            ['country_id' => $countryIndiaId, 'name' => 'Andhra Pradesh', 'code' => 'AP', 'type' => 'State', 'zone' => 'Southern', 'capital' => 'Amaravati', 'population' => '493867799', 'area' => '160205', 'language' => 'Telugu', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryIndiaId, 'name' => 'Arunachal Pradesh', 'code' => 'AR', 'type' => 'State', 'zone' => 'North-Eastern', 'capital' => 'Itanagar', 'population' => '1387276', 'area' => '83743', 'language' => 'English', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryIndiaId, 'name' => 'Assam', 'code' => 'AS', 'type' => 'State', 'zone' => 'Eastern', 'capital' => 'Dispur', 'population' => '31205576', 'area' => '78438', 'language' => 'Assamese', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryIndiaId, 'name' => 'Bihar', 'code' => 'BR', 'type' => 'State', 'zone' => 'Eastern', 'capital' => 'Patna', 'population' => '104099452', 'area' => '94163', 'language' => 'Hindi, Maithili', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryIndiaId, 'name' => 'Chhattisgarh', 'code' => 'CG', 'type' => 'State', 'zone' => 'Central', 'capital' => 'Raipur', 'population' => '25545198', 'area' => '135191', 'language' => 'Chhattisgarhi', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryIndiaId, 'name' => 'Goa', 'code' => 'GA', 'type' => 'State', 'zone' => 'Western', 'capital' => 'Panaji', 'population' => '1458545', 'area' => '3702', 'language' => 'Konkani', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryIndiaId, 'name' => 'Gujarat', 'code' => 'GJ', 'type' => 'State', 'zone' => 'Western', 'capital' => 'Gandhinagar', 'population' => '60439692', 'area' => '196024', 'language' => 'Gujarati', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryIndiaId, 'name' => 'Haryana', 'code' => 'HR', 'type' => 'State', 'zone' => 'Northern', 'capital' => 'Chandigarh', 'population' => '25351462', 'area' => '44212', 'language' => 'Hindi, Punjabi', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryIndiaId, 'name' => 'Himachal Pradesh', 'code' => 'HP', 'type' => 'State', 'zone' => 'Northern', 'capital' => 'Shimla', 'population' => '6864602', 'area' => '55673', 'language' => 'Hindi', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryIndiaId, 'name' => 'Jharkhand', 'code' => 'JH', 'type' => 'State', 'zone' => 'Eastern', 'capital' => 'Ranchi', 'population' => '32988134', 'area' => '79714', 'language' => 'Hindi, Santali', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryIndiaId, 'name' => 'Karnataka', 'code' => 'KA', 'type' => 'State', 'zone' => 'Southern', 'capital' => 'Bengaluru', 'population' => '61095297', 'area' => '191791', 'language' => 'Kannada', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryIndiaId, 'name' => 'Kerala', 'code' => 'KL', 'type' => 'State', 'zone' => 'Southern', 'capital' => 'Thiruvananthapuram', 'population' => '33406061', 'area' => '38863', 'language' => 'Malayalam', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryIndiaId, 'name' => 'Madhya Pradesh', 'code' => 'MP', 'type' => 'State', 'zone' => 'Central', 'capital' => 'Bhopal', 'population' => '72626809', 'area' => '308350', 'language' => 'Hindi', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryIndiaId, 'name' => 'Maharashtra', 'code' => 'MH', 'type' => 'State', 'zone' => 'Western', 'capital' => 'Mumbai', 'population' => '112374333', 'area' => '307713', 'language' => 'Marathi', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryIndiaId, 'name' => 'Manipur', 'code' => 'MN', 'type' => 'State', 'zone' => 'North-Eastern', 'capital' => 'Imphal', 'population' => '2855794', 'area' => '22327', 'language' => 'Meitei', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryIndiaId, 'name' => 'Meghalaya', 'code' => 'ML', 'type' => 'State', 'zone' => 'North-Eastern', 'capital' => 'Shillong', 'population' => '2966889', 'area' => '22429', 'language' => 'Khasi, Garo', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryIndiaId, 'name' => 'Mizoram', 'code' => 'MZ', 'type' => 'State', 'zone' => 'North-Eastern', 'capital' => 'Aizawl', 'population' => '1097206', 'area' => '21081', 'language' => 'Mizo', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryIndiaId, 'name' => 'Nagaland', 'code' => 'NL', 'type' => 'State', 'zone' => 'North-Eastern', 'capital' => 'Kohima', 'population' => '1980602', 'area' => '16579', 'language' => 'English', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryIndiaId, 'name' => 'Odisha', 'code' => 'OR', 'type' => 'State', 'zone' => 'Eastern', 'capital' => 'Bhubaneswar', 'population' => '41974218', 'area' => '155707', 'language' => 'Odia', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryIndiaId, 'name' => 'Punjab', 'code' => 'PB', 'type' => 'State', 'zone' => 'Northern', 'capital' => 'Chandigarh', 'population' => '27704236', 'area' => '50362', 'language' => 'Punjabi', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryIndiaId, 'name' => 'Rajasthan', 'code' => 'RJ', 'type' => 'State', 'zone' => 'Northern', 'capital' => 'Jaipur', 'population' => '68548437', 'area' => '342239', 'language' => 'Hindi', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryIndiaId, 'name' => 'Sikkim', 'code' => 'SK', 'type' => 'State', 'zone' => 'Eastern', 'capital' => 'Gangtok', 'population' => '610577', 'area' => '7096', 'language' => 'Nepali', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryIndiaId, 'name' => 'Tamil Nadu', 'code' => 'TN', 'type' => 'State', 'zone' => 'Southern', 'capital' => 'Chennai', 'population' => '72138958', 'area' => '130058', 'language' => 'Tamil', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryIndiaId, 'name' => 'Telangana', 'code' => 'TS', 'type' => 'State', 'zone' => 'Southern', 'capital' => 'Hyderabad', 'population' => '35003674', 'area' => '112077', 'language' => 'Telugu, Urdu', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryIndiaId, 'name' => 'Tripura', 'code' => 'TR', 'type' => 'State', 'zone' => 'North-Eastern', 'capital' => 'Agartala', 'population' => '3671031', 'area' => '10486', 'language' => 'Bengali', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryIndiaId, 'name' => 'Uttar Pradesh', 'code' => 'UP', 'type' => 'State', 'zone' => 'Northern', 'capital' => 'Lucknow', 'population' => '199812341', 'area' => '243286', 'language' => 'Hindi', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryIndiaId, 'name' => 'Uttarakhand', 'code' => 'UK', 'type' => 'State', 'zone' => 'Northern', 'capital' => 'Dehradun', 'population' => '10086292', 'area' => '53483', 'language' => 'Hindi', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryIndiaId, 'name' => 'West Bengal', 'code' => 'WB', 'type' => 'State', 'zone' => 'Eastern', 'capital' => 'Kolkata', 'population' => '91276115', 'area' => '88752', 'language' => 'Bengali', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],

            ['country_id' => $countryIndiaId, 'name' => 'Andaman and Nicobar Islands', 'code' => 'AN', 'type' => 'Union Territory', 'zone' => 'Southern', 'capital' => 'Port Blair', 'population' => '380581', 'area' => '8249', 'language' => 'Hindi, English', 'shipping_availability' => true, 'cash_on_delivery_availability' => false, 'status' => 1],
            ['country_id' => $countryIndiaId, 'name' => 'Chandigarh', 'code' => 'CH', 'type' => 'Union Territory', 'zone' => 'Northern', 'capital' => 'Chandigarh', 'population' => '1055450', 'area' => '114', 'language' => 'Hindi, Punjabi', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryIndiaId, 'name' => 'Dadra and Nagar Haveli and Daman and Diu', 'code' => 'DN', 'type' => 'Union Territory', 'zone' => 'Western', 'capital' => 'Daman', 'population' => '585764', 'area' => '603', 'language' => 'Gujarati, Hindi', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryIndiaId, 'name' => 'Delhi', 'code' => 'DL', 'type' => 'Union Territory', 'zone' => 'Northern', 'capital' => 'New Delhi', 'population' => '16787941', 'area' => '1484', 'language' => 'Hindi, English', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryIndiaId, 'name' => 'Jammu and Kashmir', 'code' => 'JK', 'type' => 'Union Territory', 'zone' => 'Northern', 'capital' => 'Srinagar (Summer), Jammu (Winter)', 'population' => '12267032', 'area' => '55238', 'language' => 'Urdu, Hindi', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryIndiaId, 'name' => 'Ladakh', 'code' => 'LA', 'type' => 'Union Territory', 'zone' => 'Northern', 'capital' => 'Leh', 'population' => '274289', 'area' => '59146', 'language' => 'Ladakhi, Hindi, English', 'shipping_availability' => false, 'cash_on_delivery_availability' => false, 'status' => 1],
            ['country_id' => $countryIndiaId, 'name' => 'Lakshadweep', 'code' => 'LD', 'type' => 'Union Territory', 'zone' => 'Southern', 'capital' => 'Kavaratti', 'population' => '64473', 'area' => '32', 'language' => 'Malayalam, English', 'shipping_availability' => false, 'cash_on_delivery_availability' => false, 'status' => 1],
            ['country_id' => $countryIndiaId, 'name' => 'Puducherry', 'code' => 'PY', 'type' => 'Union Territory', 'zone' => 'Southern', 'capital' => 'Puducherry', 'population' => '1247953', 'area' => '479', 'language' => 'Tamil, French, English', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
        ]);

        DB::table('states')->insert([
            ['country_id' => $countryUSAId, 'name' => 'Alabama', 'code' => 'AL', 'type' => 'State', 'zone' => 'South', 'capital' => 'Montgomery', 'population' => '5024279', 'area' => '135767', 'language' => 'English', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryUSAId, 'name' => 'Alaska', 'code' => 'AK', 'type' => 'State', 'zone' => 'West', 'capital' => 'Juneau', 'population' => '733391', 'area' => '1723337', 'language' => 'English', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryUSAId, 'name' => 'Arizona', 'code' => 'AZ', 'type' => 'State', 'zone' => 'West', 'capital' => 'Phoenix', 'population' => '7151502', 'area' => '295234', 'language' => 'English', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryUSAId, 'name' => 'Arkansas', 'code' => 'AR', 'type' => 'State', 'zone' => 'South', 'capital' => 'Little Rock', 'population' => '3011524', 'area' => '137732', 'language' => 'English', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryUSAId, 'name' => 'California', 'code' => 'CA', 'type' => 'State', 'zone' => 'West', 'capital' => 'Sacramento', 'population' => '39538223', 'area' => '423967', 'language' => 'English', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryUSAId, 'name' => 'Colorado', 'code' => 'CO', 'type' => 'State', 'zone' => 'West', 'capital' => 'Denver', 'population' => '5773714', 'area' => '269601', 'language' => 'English', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryUSAId, 'name' => 'Connecticut', 'code' => 'CT', 'type' => 'State', 'zone' => 'Northeast', 'capital' => 'Hartford', 'population' => '3605944', 'area' => '14357', 'language' => 'English', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryUSAId, 'name' => 'Delaware', 'code' => 'DE', 'type' => 'State', 'zone' => 'South', 'capital' => 'Dover', 'population' => '989948', 'area' => '6446', 'language' => 'English', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryUSAId, 'name' => 'Florida', 'code' => 'FL', 'type' => 'State', 'zone' => 'South', 'capital' => 'Tallahassee', 'population' => '21538187', 'area' => '170312', 'language' => 'English', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryUSAId, 'name' => 'Georgia', 'code' => 'GA', 'type' => 'State', 'zone' => 'South', 'capital' => 'Atlanta', 'population' => '10711908', 'area' => '153910', 'language' => 'English', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryUSAId, 'name' => 'Hawaii', 'code' => 'HI', 'type' => 'State', 'zone' => 'West', 'capital' => 'Honolulu', 'population' => '1455271', 'area' => '28313', 'language' => 'English', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryUSAId, 'name' => 'Idaho', 'code' => 'ID', 'type' => 'State', 'zone' => 'West', 'capital' => 'Boise', 'population' => '1839106', 'area' => '216443', 'language' => 'English', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryUSAId, 'name' => 'Illinois', 'code' => 'IL', 'type' => 'State', 'zone' => 'Midwest', 'capital' => 'Springfield', 'population' => '12812508', 'area' => '149995', 'language' => 'English', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryUSAId, 'name' => 'Indiana', 'code' => 'IN', 'type' => 'State', 'zone' => 'Midwest', 'capital' => 'Indianapolis', 'population' => '6785528', 'area' => '94326', 'language' => 'English', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryUSAId, 'name' => 'Iowa', 'code' => 'IA', 'type' => 'State', 'zone' => 'Midwest', 'capital' => 'Des Moines', 'population' => '3190369', 'area' => '145746', 'language' => 'English', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryUSAId, 'name' => 'Kansas', 'code' => 'KS', 'type' => 'State', 'zone' => 'Midwest', 'capital' => 'Topeka', 'population' => '2937880', 'area' => '213100', 'language' => 'English', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryUSAId, 'name' => 'Kentucky', 'code' => 'KY', 'type' => 'State', 'zone' => 'South', 'capital' => 'Frankfort', 'population' => '4505836', 'area' => '104656', 'language' => 'English', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryUSAId, 'name' => 'Louisiana', 'code' => 'LA', 'type' => 'State', 'zone' => 'South', 'capital' => 'Baton Rouge', 'population' => '4657757', 'area' => '135659', 'language' => 'English', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryUSAId, 'name' => 'Maine', 'code' => 'ME', 'type' => 'State', 'zone' => 'Northeast', 'capital' => 'Augusta', 'population' => '1362359', 'area' => '91633', 'language' => 'English', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryUSAId, 'name' => 'Maryland', 'code' => 'MD', 'type' => 'State', 'zone' => 'South', 'capital' => 'Annapolis', 'population' => '6177224', 'area' => '32131', 'language' => 'English', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryUSAId, 'name' => 'Massachusetts', 'code' => 'MA', 'type' => 'State', 'zone' => 'Northeast', 'capital' => 'Boston', 'population' => '7029917', 'area' => '27336', 'language' => 'English', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryUSAId, 'name' => 'Michigan', 'code' => 'MI', 'type' => 'State', 'zone' => 'Midwest', 'capital' => 'Lansing', 'population' => '10077331', 'area' => '250487', 'language' => 'English', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryUSAId, 'name' => 'Minnesota', 'code' => 'MN', 'type' => 'State', 'zone' => 'Midwest', 'capital' => 'Saint Paul', 'population' => '5706494', 'area' => '225163', 'language' => 'English', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryUSAId, 'name' => 'Mississippi', 'code' => 'MS', 'type' => 'State', 'zone' => 'South', 'capital' => 'Jackson', 'population' => '2961279', 'area' => '125438', 'language' => 'English', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryUSAId, 'name' => 'Missouri', 'code' => 'MO', 'type' => 'State', 'zone' => 'Midwest', 'capital' => 'Jefferson City', 'population' => '6154913', 'area' => '180540', 'language' => 'English', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryUSAId, 'name' => 'Montana', 'code' => 'MT', 'type' => 'State', 'zone' => 'West', 'capital' => 'Helena', 'population' => '1084225', 'area' => '380831', 'language' => 'English', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryUSAId, 'name' => 'Nebraska', 'code' => 'NE', 'type' => 'State', 'zone' => 'Midwest', 'capital' => 'Lincoln', 'population' => '1961504', 'area' => '200330', 'language' => 'English', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryUSAId, 'name' => 'Nevada', 'code' => 'NV', 'type' => 'State', 'zone' => 'West', 'capital' => 'Carson City', 'population' => '3104614', 'area' => '286380', 'language' => 'English', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryUSAId, 'name' => 'New Hampshire', 'code' => 'NH', 'type' => 'State', 'zone' => 'Northeast', 'capital' => 'Concord', 'population' => '1377529', 'area' => '24214', 'language' => 'English', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryUSAId, 'name' => 'New Jersey', 'code' => 'NJ', 'type' => 'State', 'zone' => 'Northeast', 'capital' => 'Trenton', 'population' => '9288994', 'area' => '22591', 'language' => 'English', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryUSAId, 'name' => 'New Mexico', 'code' => 'NM', 'type' => 'State', 'zone' => 'West', 'capital' => 'Santa Fe', 'population' => '2117522', 'area' => '314917', 'language' => 'English', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryUSAId, 'name' => 'New York', 'code' => 'NY', 'type' => 'State', 'zone' => 'Northeast', 'capital' => 'Albany', 'population' => '20201249', 'area' => '141297', 'language' => 'English', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryUSAId, 'name' => 'North Carolina', 'code' => 'NC', 'type' => 'State', 'zone' => 'South', 'capital' => 'Raleigh', 'population' => '10439388', 'area' => '139391', 'language' => 'English', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryUSAId, 'name' => 'North Dakota', 'code' => 'ND', 'type' => 'State', 'zone' => 'Midwest', 'capital' => 'Bismarck', 'population' => '779094', 'area' => '183108', 'language' => 'English', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryUSAId, 'name' => 'Ohio', 'code' => 'OH', 'type' => 'State', 'zone' => 'Midwest', 'capital' => 'Columbus', 'population' => '11799448', 'area' => '116098', 'language' => 'English', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryUSAId, 'name' => 'Oklahoma', 'code' => 'OK', 'type' => 'State', 'zone' => 'South', 'capital' => 'Oklahoma City', 'population' => '3959353', 'area' => '181037', 'language' => 'English', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryUSAId, 'name' => 'Oregon', 'code' => 'OR', 'type' => 'State', 'zone' => 'West', 'capital' => 'Salem', 'population' => '4237256', 'area' => '254799', 'language' => 'English', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryUSAId, 'name' => 'Pennsylvania', 'code' => 'PA', 'type' => 'State', 'zone' => 'Northeast', 'capital' => 'Harrisburg', 'population' => '13002700', 'area' => '119280', 'language' => 'English', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryUSAId, 'name' => 'Rhode Island', 'code' => 'RI', 'type' => 'State', 'zone' => 'Northeast', 'capital' => 'Providence', 'population' => '1097379', 'area' => '4001', 'language' => 'English', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryUSAId, 'name' => 'South Carolina', 'code' => 'SC', 'type' => 'State', 'zone' => 'South', 'capital' => 'Columbia', 'population' => '5118425', 'area' => '82933', 'language' => 'English', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryUSAId, 'name' => 'South Dakota', 'code' => 'SD', 'type' => 'State', 'zone' => 'Midwest', 'capital' => 'Pierre', 'population' => '886667', 'area' => '199729', 'language' => 'English', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryUSAId, 'name' => 'Tennessee', 'code' => 'TN', 'type' => 'State', 'zone' => 'South', 'capital' => 'Nashville', 'population' => '6910840', 'area' => '109153', 'language' => 'English', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryUSAId, 'name' => 'Texas', 'code' => 'TX', 'type' => 'State', 'zone' => 'South', 'capital' => 'Austin', 'population' => '29145505', 'area' => '695662', 'language' => 'English', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryUSAId, 'name' => 'Utah', 'code' => 'UT', 'type' => 'State', 'zone' => 'West', 'capital' => 'Salt Lake City', 'population' => '3271616', 'area' => '219882', 'language' => 'English', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryUSAId, 'name' => 'Vermont', 'code' => 'VT', 'type' => 'State', 'zone' => 'Northeast', 'capital' => 'Montpelier', 'population' => '643077', 'area' => '24906', 'language' => 'English', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryUSAId, 'name' => 'Virginia', 'code' => 'VA', 'type' => 'State', 'zone' => 'South', 'capital' => 'Richmond', 'population' => '8631393', 'area' => '110787', 'language' => 'English', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryUSAId, 'name' => 'Washington', 'code' => 'WA', 'type' => 'State', 'zone' => 'West', 'capital' => 'Olympia', 'population' => '7693612', 'area' => '184661', 'language' => 'English', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryUSAId, 'name' => 'West Virginia', 'code' => 'WV', 'type' => 'State', 'zone' => 'South', 'capital' => 'Charleston', 'population' => '1793716', 'area' => '62756', 'language' => 'English', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryUSAId, 'name' => 'Wisconsin', 'code' => 'WI', 'type' => 'State', 'zone' => 'Midwest', 'capital' => 'Madison', 'population' => '5893718', 'area' => '169635', 'language' => 'English', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1],
            ['country_id' => $countryUSAId, 'name' => 'Wyoming', 'code' => 'WY', 'type' => 'State', 'zone' => 'West', 'capital' => 'Cheyenne', 'population' => '576851', 'area' => '253335', 'language' => 'English', 'shipping_availability' => true, 'cash_on_delivery_availability' => true, 'status' => 1]
        ]);

    }
}
