<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('product_badges', function (Blueprint $table) {
            $table->id();
            $table->string('category', 50)->index(); // e.g. urgency, social_proof, promotions, newness, value, shipping
            $table->string('title', 80)->index();   // e.g. 'Best Seller'
            $table->string('slug', 100)->unique();  // e.g. best-seller
            $table->string('short', 120)->nullable(); // short label if needed
            $table->text('description')->nullable();
            $table->string('icon')->nullable(); // optional: svg class or emoji
            $table->text('tailwind_classes')->nullable();
            $table->json('meta')->nullable(); // extensible JSON for future attributes (e.g. min_stock_threshold)

            $table->integer('position')->default(1);
            $table->tinyInteger('status')->default(1)->comment('1: active, 0: inactive');
            $table->timestamps();
        });

        $now = date('Y-m-d H:i:s');

        $data = [
            // 🔥 Urgency / Scarcity
            [
                'category' => 'urgency',
                'title' => 'Limited Stock',
                'slug' => 'limited-stock',
                'short' => 'Limited Stock',
                'description' => 'Only a few units left — grab it before it sells out.',
                'icon' => '⚠️',
                'tailwind_classes' => 'bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-200',
                'meta' => json_encode(['show_when_stock_lte' => 5]),
                'position' => 1,
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 'urgency',
                'title' => 'Selling Fast',
                'slug' => 'selling-fast',
                'short' => 'Selling Fast',
                'description' => 'High demand — many customers are buying this right now.',
                'icon' => '🔥',
                'tailwind_classes' => 'bg-amber-100 text-amber-800 dark:bg-amber-900 dark:text-amber-200',
                'meta' => null,
                'position' => 2,
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 'urgency',
                'title' => 'Hurry! Few Units Remaining',
                'slug' => 'hurry-few-units-remaining',
                'short' => 'Few Units Left',
                'description' => 'Hurry — only a few units remaining in stock.',
                'icon' => '⏳',
                'tailwind_classes' => 'bg-orange-100 text-orange-800 dark:bg-orange-900 dark:text-orange-200',
                'meta' => json_encode(['show_when_stock_lte' => 10]),
                'position' => 3,
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 'urgency',
                'title' => 'Last Chance',
                'slug' => 'last-chance',
                'short' => 'Last Chance',
                'description' => 'Final opportunity to buy — won’t restock soon.',
                'icon' => '🚨',
                'tailwind_classes' => 'bg-red-50 text-red-700 dark:bg-red-800 dark:text-red-100',
                'meta' => null,
                'position' => 4,
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // ⭐ Social Proof
            [
                'category' => 'social_proof',
                'title' => 'Best Seller',
                'slug' => 'best-seller',
                'short' => 'Best Seller',
                'description' => 'Top-selling product in this category.',
                'icon' => '🏆',
                'tailwind_classes' => 'bg-emerald-100 text-emerald-800 dark:bg-emerald-900 dark:text-emerald-200',
                'meta' => json_encode(['apply_when_rank_lte' => 10]),
                'position' => 1,
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 'social_proof',
                'title' => 'Top Rated',
                'slug' => 'top-rated',
                'short' => 'Top Rated',
                'description' => 'Highly rated by customers.',
                'icon' => '⭐',
                'tailwind_classes' => 'bg-sky-100 text-sky-800 dark:bg-sky-900 dark:text-sky-200',
                'meta' => json_encode(['min_rating' => 4.5]),
                'position' => 2,
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 'social_proof',
                'title' => 'Most Loved',
                'slug' => 'most-loved',
                'short' => 'Most Loved',
                'description' => 'Loved by thousands of customers.',
                'icon' => '💖',
                'tailwind_classes' => 'bg-pink-100 text-pink-800 dark:bg-pink-900 dark:text-pink-200',
                'meta' => null,
                'position' => 3,
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 'social_proof',
                'title' => 'Customer Favorite',
                'slug' => 'customer-favorite',
                'short' => 'Customer Favorite',
                'description' => 'Frequently chosen and highly rated by customers.',
                'icon' => '❤️',
                'tailwind_classes' => 'bg-rose-50 text-rose-700 dark:bg-rose-900 dark:text-rose-200',
                'meta' => null,
                'position' => 4,
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 'social_proof',
                'title' => 'Hot Pick',
                'slug' => 'hot-pick',
                'short' => 'Hot Pick',
                'description' => 'Handpicked popular product.',
                'icon' => '🔥',
                'tailwind_classes' => 'bg-amber-100 text-amber-800 dark:bg-amber-900 dark:text-amber-200',
                'meta' => null,
                'position' => 5,
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 🎁 Promotions
            [
                'category' => 'promotions',
                'title' => 'Special Offer',
                'slug' => 'special-offer',
                'short' => 'Special Offer',
                'description' => 'Limited-time special pricing.',
                'icon' => '🎉',
                'tailwind_classes' => 'bg-violet-100 text-violet-800 dark:bg-violet-900 dark:text-violet-200',
                'meta' => null,
                'position' => 1,
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 'promotions',
                'title' => 'Deal of the Day',
                'slug' => 'deal-of-the-day',
                'short' => 'Deal of the Day',
                'description' => 'Special daily deal with limited time pricing.',
                'icon' => '💥',
                'tailwind_classes' => 'bg-pink-100 text-pink-800 dark:bg-pink-900 dark:text-pink-200',
                'meta' => json_encode(['starts_at' => null, 'ends_at' => null]),
                'position' => 2,
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 'promotions',
                'title' => "Today's Pick",
                'slug' => 'todays-pick',
                'short' => 'Today’s Pick',
                'description' => 'Editor’s pick for the day.',
                'icon' => '📌',
                'tailwind_classes' => 'bg-yellow-100 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-200',
                'meta' => null,
                'position' => 3,
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 'promotions',
                'title' => 'Buy 1 Get 1',
                'slug' => 'buy-1-get-1',
                'short' => 'Buy 1 Get 1',
                'description' => 'Buy one get one free (applies at checkout).',
                'icon' => '🎁',
                'tailwind_classes' => 'bg-indigo-100 text-indigo-800 dark:bg-indigo-900 dark:text-indigo-200',
                'meta' => json_encode(['type' => 'bogo']),
                'position' => 4,
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 'promotions',
                'title' => 'Flash Sale',
                'slug' => 'flash-sale',
                'short' => 'Flash Sale',
                'description' => 'Short-duration flash sale — limited quantities.',
                'icon' => '⚡',
                'tailwind_classes' => 'bg-red-50 text-red-700 dark:bg-red-800 dark:text-red-100',
                'meta' => json_encode(['is_flash' => true]),
                'position' => 5,
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 🆕 Newness / Exclusivity
            [
                'category' => 'newness',
                'title' => 'New Arrival',
                'slug' => 'new-arrival',
                'short' => 'New',
                'description' => 'Recently added to our store.',
                'icon' => '🆕',
                'tailwind_classes' => 'bg-indigo-100 text-indigo-800 dark:bg-indigo-900 dark:text-indigo-200',
                'meta' => json_encode(['show_when_added_days_lte' => 30]),
                'position' => 1,
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 'newness',
                'title' => 'Exclusive',
                'slug' => 'exclusive',
                'short' => 'Exclusive',
                'description' => 'Only available here — exclusive product.',
                'icon' => '🔒',
                'tailwind_classes' => 'bg-amber-50 text-amber-800 dark:bg-amber-900 dark:text-amber-200',
                'meta' => null,
                'position' => 2,
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 'newness',
                'title' => 'Just Launched',
                'slug' => 'just-launched',
                'short' => 'Just Launched',
                'description' => 'Freshly launched — try it now.',
                'icon' => '🚀',
                'tailwind_classes' => 'bg-emerald-50 text-emerald-800 dark:bg-emerald-900 dark:text-emerald-200',
                'meta' => null,
                'position' => 3,
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 'newness',
                'title' => 'Limited Edition',
                'slug' => 'limited-edition',
                'short' => 'Limited Edition',
                'description' => 'Special limited edition product — exclusive run.',
                'icon' => '✨',
                'tailwind_classes' => 'bg-amber-50 text-amber-800 dark:bg-amber-900 dark:text-amber-200',
                'meta' => null,
                'position' => 4,
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 'newness',
                'title' => 'Premium Pick',
                'slug' => 'premium-pick',
                'short' => 'Premium Pick',
                'description' => 'Curated premium selection for discerning buyers.',
                'icon' => '💎',
                'tailwind_classes' => 'bg-slate-100 text-slate-800 dark:bg-slate-800 dark:text-slate-200',
                'meta' => null,
                'position' => 5,
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 💰 Value
            [
                'category' => 'value',
                'title' => 'Lowest Price',
                'slug' => 'lowest-price',
                'short' => 'Lowest Price',
                'description' => 'Lowest price available across sellers.',
                'icon' => '🔖',
                'tailwind_classes' => 'bg-slate-100 text-slate-800 dark:bg-slate-900 dark:text-slate-200',
                'meta' => null,
                'position' => 1,
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 'value',
                'title' => 'Value Pack',
                'slug' => 'value-pack',
                'short' => 'Value Pack',
                'description' => 'Bundle or multi-pack offering better unit price.',
                'icon' => '📦',
                'tailwind_classes' => 'bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200',
                'meta' => json_encode(['bundle' => true]),
                'position' => 2,
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 'value',
                'title' => 'Budget Friendly',
                'slug' => 'budget-friendly',
                'short' => 'Budget Friendly',
                'description' => 'Affordable option without compromising quality.',
                'icon' => '💸',
                'tailwind_classes' => 'bg-emerald-50 text-emerald-800 dark:bg-emerald-900 dark:text-emerald-200',
                'meta' => null,
                'position' => 3,
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 'value',
                'title' => 'Great Savings',
                'slug' => 'great-savings',
                'short' => 'Great Savings',
                'description' => 'Excellent price for the features offered.',
                'icon' => '💰',
                'tailwind_classes' => 'bg-lime-100 text-lime-800 dark:bg-lime-900 dark:text-lime-200',
                'meta' => json_encode(['min_discount_pct' => 10]),
                'position' => 4,
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 'value',
                'title' => 'Best Value',
                'slug' => 'best-value',
                'short' => 'Best Value',
                'description' => 'Best combination of price and features.',
                'icon' => '🏷️',
                'tailwind_classes' => 'bg-sky-50 text-sky-800 dark:bg-sky-900 dark:text-sky-200',
                'meta' => null,
                'position' => 5,
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 🚚 Delivery / Assurance
            [
                'category' => 'logistics',
                'title' => 'Express Delivery',
                'slug' => 'express-delivery',
                'short' => 'Express Delivery',
                'description' => 'Fast delivery options available for this product.',
                'icon' => '🚚',
                'tailwind_classes' => 'bg-cyan-100 text-cyan-800 dark:bg-cyan-900 dark:text-cyan-200',
                'meta' => json_encode(['estimate_days' => [1,2]]),
                'position' => 1,
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 'logistics',
                'title' => 'Fastest Shipping',
                'slug' => 'fastest-shipping',
                'short' => 'Fastest Shipping',
                'description' => 'Top-tier shipping speed for this product.',
                'icon' => '⚡',
                'tailwind_classes' => 'bg-indigo-100 text-indigo-800 dark:bg-indigo-900 dark:text-indigo-200',
                'meta' => json_encode(['priority_shipping' => true]),
                'position' => 2,
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 'assurance',
                'title' => 'Assured Quality',
                'slug' => 'assured-quality',
                'short' => 'Assured Quality',
                'description' => 'Quality checks performed — guaranteed authenticity.',
                'icon' => '✔️',
                'tailwind_classes' => 'bg-slate-100 text-slate-800 dark:bg-slate-800 dark:text-slate-200',
                'meta' => null,
                'position' => 3,
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 'assurance',
                'title' => 'Warranty Included',
                'slug' => 'warranty-included',
                'short' => 'Warranty',
                'description' => 'Manufacturer warranty included with this item.',
                'icon' => '🔒',
                'tailwind_classes' => 'bg-slate-50 text-slate-800 dark:bg-slate-800 dark:text-slate-200',
                'meta' => json_encode(['warranty_months' => 12]),
                'position' => 4,
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category' => 'assurance',
                'title' => '100% Genuine',
                'slug' => '100-percent-genuine',
                'short' => '100% Genuine',
                'description' => 'Authentic products from verified sellers.',
                'icon' => '✅',
                'tailwind_classes' => 'bg-green-50 text-green-800 dark:bg-green-900 dark:text-green-200',
                'meta' => null,
                'position' => 5,
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        // Insert into DB
        DB::table('product_badges')->insert($data);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('product_badges');
    }
};
